### ISSUE TITLE
[공유] 스터디 주제 Scope & Closures

### ISSUE THREAD

**Issue by songeunwoo** [organic-benefit/all-about-study#2]
다음주 스터디 주제로 You-Dont-Know-JS을 분석하자는 의견으로 모였습니다.

그 첫번째 시간으로 
**You Don't Know JS: Scope & Closures**
에 대해서 스터디 및 분석을 하기로 하였습니다.

해당 책의 발표 순서는 하기와 같다.
- Chapter 1: What is Scope? : 김동철
- Chapter 2: Lexical Scope : 장기석
- Chapter 3: Function vs. Block Scope : 손근우
- Chapter 4: Hoisting : 주민혁
- Chapter 5: Scope Closures : 정종철

각각 챕터별로 발표 준비를 하시면 됩니다.
해당 책은 무료로 read 할수 있으니 참고 하세요.
하기에 링크 붙여 드립니다.
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/README.md#you-dont-know-js-scope--closures

**Comment by doublemetal** [comment]
감사합니다. 제 자료는 아래 주소에 업로드하겠습니다.
https://github.com/organic-benefit/all-about-study/blob/master/docs/ydk/scope-and-closures/chapter1-what-is-scope.md
